services:
  vprodb:
    build:
      context: .
      dockerfile: Docker-files/db/Dockerfile
    image: tabarak23/vprodb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: .
      dockerfile: Docker-files/app/Dockerfile
    image: tabarak23/vproapp
    container_name: vproapp
    ports:
      - "8080:8080"
    depends_on:
      - vprodb
      - vprocache01
      - vpromq01

  vproweb:
    build:
      context: .
      dockerfile: Docker-files/web/Dockerfile
    image: tabarak23/vproweb
    container_name: vproweb
    ports:
      - "80:80"
    depends_on:
      - vproapp

volumes:
  vprodbdata: {}
